const endpoint = '/api', dialog = document.querySelector('#log-dialog'), logOutput = document.querySelector('#log-output'); let snapshot = { bots: [], logs: [] };
async function request(path, body) { const response = await fetch(`${endpoint}${path}`, { method: body ? 'POST' : path === '/status' ? 'GET' : 'POST', headers: body ? { 'Content-Type': 'application/json' } : {}, body: body ? JSON.stringify(body) : undefined }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Không thể kết nối máy chủ điều khiển.'); return data; }
function formatUptime(time) { const s = Math.max(0, Math.floor((Date.now() - new Date(time)) / 1000)), h = Math.floor(s / 3600), m = Math.floor((s % 3600) / 60); return h > 24 ? `${Math.floor(h / 24)}d ${h % 24}h` : `${h}h ${m}m`; }
function updateCard(bot) { const card = document.querySelector(`[data-bot="${bot.id}"]`); if (!card) return; const label = card.querySelector('.status'); label.className = `status ${bot.running ? 'online' : 'offline'}`; label.innerHTML = `<i></i> ${bot.running ? 'Đang chạy' : 'Đã dừng'}`; card.querySelector('dd').textContent = bot.running ? formatUptime(bot.startedAt) : '—'; const button = card.querySelector('.button.stop'); button.textContent = bot.running ? '■ Dừng' : '▶ Chạy'; button.dataset.action = bot.running ? 'stop' : 'start'; }
function drawLogs(filter) { const items = snapshot.logs.filter(item => !filter || item.bot === filter).slice(0, 60); logOutput.textContent = items.length ? items.map(item => `[${new Date(item.time).toLocaleTimeString('vi-VN')}] ${item.bot}: ${item.message}`).join('\n') : 'Chưa có nhật ký.'; }
async function refresh() { snapshot = await request('/status'); snapshot.bots.forEach(updateCard); const online = snapshot.bots.filter(bot => bot.running).length; document.querySelector('.stats article strong').innerHTML = `${online} <small>/ 4</small>`; if (dialog.open) drawLogs(); }
document.addEventListener('click', async event => { const button = event.target.closest('[data-action]'); if (!button) return; const action = button.dataset.action, card = button.closest('[data-bot]'); if (action === 'logs') { drawLogs(card?.dataset.bot); dialog.showModal(); return; } button.disabled = true; try { if (action === 'refresh') await refresh(); else if (action.endsWith('-all')) await request(`/bots/${action}`); else await request(`/bots/${card.dataset.bot}/${action}`); await new Promise(resolve => setTimeout(resolve, 250)); await refresh(); } catch (error) { alert(error.message); } finally { button.disabled = false; } });
document.querySelector('[data-close-log]').addEventListener('click', () => dialog.close()); refresh().catch(() => {}); setInterval(() => refresh().catch(() => {}), 5000);
function formData(form) { return Object.fromEntries(new FormData(form).entries()); }
document.querySelector('#member-form').addEventListener('submit', async event => { event.preventDefault(); const form = event.currentTarget, data = formData(form), message = document.querySelector('#member-message'); const body = { guildId: data.guildId.trim(), userId: data.userId.trim(), action: data.action }; if (data.action === 'nickname') body.nickname = data.value.trim(); if (data.action.endsWith('role')) body.roleId = data.value.trim(); try { await request('/discord/member', body); message.textContent = '✓ Đã cập nhật thành viên thành công.'; message.className = 'form-message success-message'; } catch (error) { message.textContent = `✕ ${error.message}`; message.className = 'form-message error-message'; } });
document.querySelector('#fish-form').addEventListener('submit', async event => { event.preventDefault(); const data = formData(event.currentTarget), message = document.querySelector('#fish-message'); try { const result = await request('/fish', { userId: data.userId.trim(), action: data.action, amount: Number(data.amount) }); message.textContent = `✓ Số dư hiện tại: ${Number(result.balance).toLocaleString('vi-VN')} cá.`; message.className = 'form-message success-message'; } catch (error) { message.textContent = `✕ ${error.message}`; message.className = 'form-message error-message'; } });
